package com.val.persistence.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity(name="usuario")
@Table(name = "usuario", catalog = "bd_muestra", uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class UsuarioE implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1472126760045028941L;
	
	private Integer idUsuario;
	private String nombre;
	private String pwd;
	private String email;
	private String telefono;
	private String web;

	public UsuarioE() {
	}

	public UsuarioE(String nombre) {
		this.nombre = nombre;
	}

	public UsuarioE(String nombre, String pwd, String email, String telefono, String web) {
		this.nombre = nombre;
		this.pwd = pwd;
		this.email = email;
		this.telefono = telefono;
		this.web = web;
	}

	public UsuarioE(String nombre2, String pwd2) {
		this.nombre = nombre2;
		this.pwd = pwd2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_usuario", unique = true, nullable = false)
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "nombre", unique = true, nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "pwd", length = 45)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telefono", length = 20)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "web", length = 120)
	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

}
